FROM golang:1.17.1 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.14.0

COPY --from=builder /app/pro-check-server /bin/pro-check-server
WORKDIR /var/lib/pro-check-server/

CMD ["/bin/pro-check-server"]
